FROM node:10

WORKDIR /App

# Install Node Red
RUN npm install -g --unsafe-perm node-red

# Install the dashboard extension
WORKDIR /usr/local/lib/node_modules/node-red/node_modules/
RUN npm install node-red-dashboard

# Install Azure IoT Edge Module nodes
RUN npm install node-red-contrib-azure-iot-edge-module

WORKDIR /App

EXPOSE 1880/tcp

USER node

CMD ["node-red", "--flowFile", "flows.json", "--userDir", "/node-red/"]
